version: '2'
services:
  nextcloud:
    restart: always
    image: sameersbn/nextcloud:9.0.55
    command: app:nextcloud
    environment:
    - DEBUG=false
    - TZ=Asia/Bangkok

    - DB_TYPE=pgsql
    - DB_HOST=10.2.0.130
    - DB_USER=nextcloud
    - DB_PASS=4awefa3
    - DB_NAME=nextcloud

    - NEXTCLOUD_URL=http://cloud.jasmine.com:10080

    - NEXTCLOUD_ADMIN_USER=admin
    - NEXTCLOUD_ADMIN_PASSWORD=aeafw3awef

    - NEXTCLOUD_UPLOAD_MAX_FILESIZE=4G
    - NEXTCLOUD_MAX_FILE_UPLOADS=20

    - NEXTCLOUD_BACKUPS_EXPIRY=0
    depends_on:
    - postgresql
    volumes:
     - data:/mnt/ceph_storage/data
     - config:/var/www/html/config
     - apps:/var/www/html/apps

  nginx:
    restart: always
    image: sameersbn/nextcloud:9.0.55
    command: app:nginx
    environment:
    - NEXTCLOUD_PHP_FPM_HOST=nextcloud
    - NEXTCLOUD_PHP_FPM_PORT=9000
    depends_on:
    - nextcloud
    ports:
    - "10080:80"
